plugins = [
  "2hop-links-plus",
  "dataview",
  "obsidian-auto-link-title",
  "obsidian-chartsview-plugin",
  "obsidian-task-archiver",
  "obsidian-tasks-plugin",
  "obsidian-linter",
  "easy-typing-obsidian",
  "copy-inline-code",
  "obsidian-outliner",
  "code-styler",
  "colored-tags",
  "darlal-switcher-plus",
  "shukuchi",
  "typewriter-mode",
  "various-complements",
  "notebook-navigator",
  "obsidian-vimrc-support",
  "obsidian-meta-bind-plugin",
  "obsidian-advanced-uri",
  "spacekeys",
  "auto-close-oldest-tabs",
]

themes = [
  "Obsidian gruvbox",
]

active_theme = "Obsidian gruvbox"

vim_mode = true
show_line_number = true

hotkeys = "obsidian-settings/hotkeys.json"
command_palette = "obsidian-settings/command-palette.json"

[fonts]
interface = "Maple Mono NF CN"
text = "Maple Mono NF CN"
monospace = "Maple Mono NF CN"

[[vault_files]]
source = "vault-files/.obsidian.vimrc"
target = ".obsidian.vimrc"

[[vault_files]]
source = "vault-files/spacekeys.yml"
target = "spacekeys.yml"

[plugin_settings]
obsidian-auto-link-title = "plugin-settings/obsidian-auto-link-title"
obsidian-linter = "plugin-settings/obsidian-linter"
easy-typing-obsidian = "plugin-settings/easy-typing-obsidian"
various-complements = "plugin-settings/various-complements"
notebook-navigator = "plugin-settings/notebook-navigator"
spacekeys = "plugin-settings/spacekeys"
auto-close-oldest-tabs = "plugin-settings/auto-close-oldest-tabs"
