plugins = [
  "2hop-links-plus",
  "dataview",
  "obsidian-auto-link-title",
  "obsidian-chartsview-plugin",
  "obsidian-task-archiver",
  "obsidian-tasks-plugin",
  "obsidian-linter",
  "easy-typing-obsidian",
  "copy-inline-code",
  "obsidian-outliner",
  "code-styler",
  "colored-tags",
  "darlal-switcher-plus",
  "shukuchi",
  "typewriter-mode",
  "open-tab-settings",
  "various-complements",
  "notebook-navigator",
  "obsidian-vimrc-support",
  "obsidian-meta-bind-plugin",
  "obsidian-advanced-uri",
  "spacekeys",
]

themes = [
  "Obsidian gruvbox",
]

active_theme = "Obsidian gruvbox"

vim_mode = true

hotkeys = "obsidian-settings/hotkeys.json"

[[vault_files]]
source = "vault-files/.obsidian.vimrc"
target = ".obsidian.vimrc"

[[vault_files]]
source = "vault-files/spacekeys.yml"
target = "spacekeys.yml"

[plugin_settings]
obsidian-linter = "plugin-settings/obsidian-linter"
various-complements = "plugin-settings/various-complements"
notebook-navigator = "plugin-settings/notebook-navigator"
spacekeys = "plugin-settings/spacekeys"
